apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.portal" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
{{- if  (eq .Values.expose.ingress.controller "gce-internal") }}
  annotations:
    cloud.google.com/neg: '{ "ingress": true }'
{{- end }}
spec:
  ports:
    - port: {{ template "harbor.portal.servicePort" . }}
      targetPort: {{ template "harbor.portal.containerPort" . }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
